In [46]:
import pandas as pd

In [47]:
df = pd.read_csv("bhatbhateni_sales.csv")

In [48]:
df.head()

,TransactionID,Date,CustomerID,CustomerName,Branch,ProductCategory,ProductName,Quantity,UnitPrice,TotalAmount,PaymentMethod
0,TXN101590,2025-05-19,CUST1100,Sujan Shrestha,Pokhara - Lakeside,Bakery,Chocolate Cake Slice,2,171.29,342.58,Khalti
1,TXN103282,2025-03-07,CUST1005,Milan Lama,Butwal - Traffic Chowk,Personal Care,Dove Soap,3,149.59,448.77,eSewa
2,TXN103539,2025-10-05,CUST1130,Alina Rai,Bhaktapur - Suryabinayak,Apparel,Winter Jacket,4,2794.25,11177.00,Khalti
3,TXN102479,2025-11-12,CUST1057,Neha Karki,Kathmandu - New Road,Household,Surf Excel 1kg,4,399.62,1598.48,Cash
4,TXN104408,2025-10-09,CUST1005,Milan Lama,Butwal - Traffic Chowk,Beverages,Gorkha Beer (6-pack),2,281.01,562.02,eSewa

In [49]:
print("Columns names")
for col_name in df.columns:
    print(col_name)

Columns names
TransactionID
Date
CustomerID
CustomerName
Branch
ProductCategory
ProductName
Quantity
UnitPrice
TotalAmount
PaymentMethod

In [50]:
print("Rows: ", df.shape[0], "Columns: ", df.shape[1])

Rows:  18812 Columns:  11

In [51]:
print(df.dtypes)

TransactionID          str
Date                   str
CustomerID             str
CustomerName           str
Branch                 str
ProductCategory        str
ProductName            str
Quantity             int64
UnitPrice          float64
TotalAmount        float64
PaymentMethod          str
dtype: object

In [52]:
df.describe()

           Quantity     UnitPrice   TotalAmount
count  18812.000000  18441.000000  18812.000000
mean       2.506804    728.803530   1819.990565
std        1.114328    766.346109   2241.968350
min        1.000000     40.140000     40.610000
25%        2.000000    240.160000    488.397500
50%        3.000000    416.780000    989.000000
75%        3.000000    848.320000   2142.545000
max        4.000000   3499.280000  13997.120000

In [53]:
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

missing = missing[missing["Missing Count"] > 0]

print(missing)

                 Missing Count  Missing Percentage
CustomerName               568            3.019349
ProductCategory            282            1.499043
UnitPrice                  371            1.972145
PaymentMethod              468            2.487774

In [54]:
duplicate = df.duplicated().sum()
print ("Fully duplicated rows = ", duplicate)

Fully duplicated rows =  724

In [55]:
df[df.duplicated(subset=["TransactionID"], keep=False)]

,TransactionID,Date,CustomerID,CustomerName,Branch,ProductCategory,ProductName,Quantity,UnitPrice,TotalAmount,PaymentMethod
0,TXN101590,2025-05-19,CUST1100,Sujan Shrestha,Pokhara - Lakeside,Bakery,Chocolate Cake Slice,2,171.29,342.58,Khalti
1,TXN103282,2025-03-07,CUST1005,Milan Lama,Butwal - Traffic Chowk,Personal Care,Dove Soap,3,149.59,448.77,eSewa
2,TXN103539,2025-10-05,CUST1130,Alina Rai,Bhaktapur - Suryabinayak,Apparel,Winter Jacket,4,2794.25,11177.00,Khalti
3,TXN102479,2025-11-12,CUST1057,Neha Karki,Kathmandu - New Road,Household,Surf Excel 1kg,4,399.62,1598.48,Cash
4,TXN104408,2025-10-09,CUST1005,Milan Lama,Butwal - Traffic Chowk,Beverages,Gorkha Beer (6-pack),2,281.01,562.02,eSewa
...,...,...,...,...,...,...,...,...,...,...,...
18807,TXN102758,2025-09-22,CUST1110,Sushma Karki,Kathmandu - New Road,Electronics,USB Cable Type-C,1,429.82,429.82,Cash
18808,TXN105279,2025-12-14,CUST1031,Sabnam Khadka,Bhaktapur - Suryabinayak,Grocery,Sugar 1kg,1,546.90,546.90,Cash
18809,TXN102971,2025-05-11,CUST1002,Kritika Bhattarai,Butwal - Traffic Chowk,Dairy,DDC Milk 1L,3,129.40,388.20,Debit/Credit Card
18810,TXN101435,2025-10-06,CUST1031,NaN,Bhaktapur - Suryabinayak,Electronics,Wall Clock,2,781.61,1563.22,Cash
18811,TXN105017,2025-01-07,CUST1136,Bikash Gurung,Bhaktapur - Suryabinayak,Electronics,Power Bank 10000mAh,4,3280.42,13121.68,Cash